src/Template/Template.WebApp/Areas/Administration/Controllers/RolesController.cs
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.EntityFrameworkCore;
using Template.Common;
using Template.Domain.Entities.Identity;
using Template.WebApp.Areas.Administration.Models;
using Template.Security.Authorization;
using Template.Security.DataProtection;
using Template.Application.Features.IdentityContext.Services;

namespace Template.WebApp.Areas.Administration.Controllers
{
    [Authorize(Roles = RoleGroup.SuperadminAndAdminRoles)]
    public class RolesController : BaseAdministrationController
    {
        private readonly IDataProtector protector;

        public RolesController(IMediator mediator, UserManager userManager, RoleManager roleManager, IHtmlLocalizer localizer, IDataProtectionProvider dataProtectionProvider) : base(mediator, userManager, roleManager, localizer)
        {
            //TODO: Encrypt routvalues
            this.protector = dataProtectionProvider.CreateProtector(ProtectionPurpose.RoleIdRouteValue);
        }

        public async Task<IActionResult> Index()
        {
            var superadminRole = await roleManager.Roles.Where(r => r.Name == Roles.Superadmin).ToListAsync();
            var allRoles = await roleManager.Roles.ToListAsync();

            var allRolesExceptSuperadmin = allRoles.Except(superadminRole).ToList();

            var user = await userManager.FindByNameAsync(User.Identity.Name);
            List<Role> roles = await userManager.IsInRoleAsync(user, Roles.Superadmin) ? allRoles : allRolesExceptSuperadmin;

            return View(roles);
        }

        [HttpGet]
        [Authorize(Policy = Roles.Superadmin)]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Policy = Roles.Superadmin)]
        public async Task<IActionResult> Create(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                Role role = new Role()
                {
                    Name = model.RoleName
                };

                var result = await roleManager.CreateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }

                foreach (var error in result.Errors)
                {
                    //TODO: Crear constante y revisar modelo de manejo de errores
                    ModelState.AddModelError(Constants.KeyErrors.ValidationError, error.Description);
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var role = await roleManager.FindByIdAsync(id);

            if (role == null)
            {
                //TODO: Crear constante y revisar modelo de manejo de errores
                ModelState.AddModelError(Constants.KeyErrors.ValidationError, "Role not found");
            }

            var model = new EditRoleViewModel
            {
                Id = role.Id,
                RoleName = role.Name,
                Users = (await userManager.GetUsersInRoleAsync(role.Name)).Select(u => u.UserName).ToList()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                Role role = await roleManager.FindByIdAsync(model.Id);

                if (role == null)
                {
                    //TODO: Crear constante y revisar modelo de manejo de errores
                    ModelState.AddModelError(Constants.KeyErrors.ValidationError, "Role not found");
                }
                else
                {
                    role.Name = model.RoleName;

                    var result = await roleManager.UpdateAsync(role);

                    if (result.Succeeded)
                    {
                        return RedirectToAction(nameof(Index));
                    }

                    foreach (var error in result.Errors)
                    {
                        //TODO: Crear constante y revisar modelo de manejo de errores
                        ModelState.AddModelError(Constants.KeyErrors.ValidationError, error.Description);
                    }
                }
            }

            return View(model);
        }

        [HttpPost]
        [Authorize(Policy = Roles.Superadmin)]
        public async Task<IActionResult> Delete(string id)
        {
            //TODO: Agregar confirmación antes de eliminar un usuario
            //TODO: Agregar clases para soft delete a las entidades
            //TODO: Agregar auditoria a las entidades

            Role role = await roleManager.FindByIdAsync(id);

            if (role == null)
            {
                //TODO: Crear constante y revisar modelo de manejo de errores
                ModelState.AddModelError(Constants.KeyErrors.ValidationError, "Role not found");
            }
            else
            {
                var result = await roleManager.DeleteAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }

                foreach (var error in result.Errors)
                {
                    //TODO: Revisar modelo de manejo de errores
                    ModelState.AddModelError(Constants.KeyErrors.ValidationError, error.Description);
                }
            }

            return View(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> UsersInRole(string id)
        {
            ViewBag.RoleId = id;
            var role = await roleManager.FindByIdAsync(id);
            var loggedUser = await userManager.FindByNameAsync(User.Identity.Name);

            if (role == null)
            {
                //TODO: Crear constante y revisar modelo de manejo de errores
                ModelState.AddModelError(Constants.KeyErrors.ValidationError, "Role not found");
            }

            var model = new List<UserRoleViewModel>();

            var users = new List<User>();
            var allUsers = await userManager.Users.Where(u => u.Id != loggedUser.Id).ToListAsync();

            var allUsersExceptLoggedUser = allUsers.Except(new List<User> { loggedUser }).ToList();
            users = await userManager.IsInRoleAsync(loggedUser, Roles.Superadmin) ? allUsers : allUsersExceptLoggedUser;


            foreach (var user in users)
            {
                model.Add(new UserRoleViewModel()
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    IsSelected = await userManager.IsInRoleAsync(user, role.Name)
                });
            }

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> UsersInRole(List<UserRoleViewModel> model, string id)
        {
            var role = await roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ModelState.AddModelError(Constants.KeyErrors.ValidationError, "Role not found");
            }

            for (int i = 0; i < model.Count; i++)
            {
                var user = await userManager.FindByIdAsync(model[i].UserId);

                IdentityResult result = null;

                var isInRole = await userManager.IsInRoleAsync(user, role.Name);
                if (model[i].IsSelected && !isInRole)
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                }
                else if (!model[i].IsSelected && isInRole)
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if (result.Succeeded)
                {
                    if (i < (model.Count - 1))
                        continue;
                    else
                        return RedirectToAction(nameof(Edit), new { id });
                }
            }

            return RedirectToAction(nameof(Edit), new { id });
        }
    }
}

src/Template/Template.WebApp/Areas/SampleAjax/Controllers/SampleListController.cs
using Mapster;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using System.Security.Claims;
using Template.Application.Features.IdentityContext.Services;
using Template.Application.Features.SampleContext.Contracts.DTOs;
using Template.Application.Features.SampleContext.Items.Command;
using Template.Application.Features.SampleContext.Items.Query;
using Template.Application.Features.SampleContext.Lists.Command;
using Template.Application.Features.SampleContext.Lists.Query;
using Template.Common.TypesExtensions;
using Template.Domain.Entities.Shared;
using Template.WebApp.Areas.SampleAjax.Models.SampleList;
using Template.WebApp.Services.Rendering;
using Result = Template.Domain.Entities.Shared.Result;

namespace Template.WebApp.Areas.SampleAjax.Controllers
{
    public class SampleListController : BaseSampleController
    {
        private readonly IRazorViewRenderer razorViewRenderer;

        public SampleListController(IRazorViewRenderer razorViewRenderer, IMediator mediator, UserManager userManager, IHtmlLocalizer localizer) : base(mediator, userManager, localizer)
        {
            this.razorViewRenderer = razorViewRenderer;
        }

        public ClaimsPrincipal UserPrincipal => HttpContext?.User!;

        public async Task<IActionResult> Index(CancellationToken cancellationToken)
        {
            var result = await ListByLoggedUserAsync(cancellationToken);

            return View(result.IsSuccess ? result.Value.Adapt<List<SampleListWithItemCountsViewModel>>() : new List<SampleListWithItemCountsViewModel>());
        }

        public async Task<IActionResult> List(CancellationToken cancellationToken)
        {
            var result = await ListByLoggedUserAsync(cancellationToken);

            return Json(result.IsSuccess ? result.Value.Adapt<List<SampleListWithItemCountsViewModel>>() : new List<SampleListWithItemCountsViewModel>());
        }

        public async Task<IActionResult> Detail(int id, CancellationToken cancellationToken)
        {
            var result = await GetSampleListByIdAsync(id, cancellationToken: cancellationToken);

            return View(result.Value.Adapt<SampleListViewModel>());

        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(SampleListViewModel sampleListViewModel, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.GetUserAsync(UserPrincipal);

                var createListResult = await mediator.Send(new CreateSampleList.Command(user, sampleListViewModel.Name), cancellationToken);

                if (createListResult.IsFailure)
                {
                    HandleFailureResult(createListResult);
                    return View(sampleListViewModel);
                }

                if (createListResult.IsSuccess && !sampleListViewModel.Items.IsNullOrEmpty())
                {
                    var addItemsResult = await mediator.Send(new AddSampleItemsToList.Command(createListResult.Value, sampleListViewModel.Items.Adapt<List<SampleItemDto>>()));

                    if (addItemsResult.IsFailure)
                    {
                        HandleFailureResult(createListResult);
                        return View(sampleListViewModel);
                    }

                }

                var sampleListId = createListResult.Value;
                return RedirectToAction(nameof(Edit), new { id = sampleListId });
            }
            return View(sampleListViewModel);
        }

        public async Task<IActionResult> Edit(int id, CancellationToken cancellationToken)
        {
            var result = await GetSampleListByIdAsync(id, "Edit", cancellationToken);

            var model = result.Value.Adapt<EditSampleListViewModel>();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditSampleListViewModel sampleListViewModel, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                var result = await mediator.Send(
                    new UpdateSampleList.Command(
                        sampleListViewModel.Id,
                        sampleListViewModel.Name,
                        sampleListViewModel.UserId), cancellationToken);

                if (result.IsFailure)
                {
                    return Json(GetFailureMessageResponse(result, "Edit"));
                }
                else
                {
                    return Json(GetSuccessMessageResponse(localizer["Sample_SampleList_Edit_Success"].Value, "Edit"));
                }
            }
            return View(sampleListViewModel);
        }

        public async Task<IActionResult> Delete(int id, CancellationToken cancellationToken = default)
        {
            var result = await GetSampleListByIdAsync(id, cancellationToken: cancellationToken);

            var model = new DeleteSampleListViewModel();
            if (result.IsSuccess)
            {
                var sampleList = result.Value.Adapt<SampleListViewModel>();
                model = new DeleteSampleListViewModel()
                {
                    ListId = sampleList.Id,
                    ListName = sampleList.Name,
                    ItemsCount = sampleList.ItemsCount,
                    HasItems = sampleList.Items.Any()
                };
            }

            return PartialView("_Delete", model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(DeleteSampleListViewModel deleteSampleListViewModel, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                var result = await mediator.Send(
                    new DeleteSampleList.Command(deleteSampleListViewModel.ListId),
                    cancellationToken);

                if (result.IsSuccess)
                {
                    return Json(GetSuccessMessageResponse(localizer.GetString("Sample_SampleList_Delete_Success")));
                }
                else
                {
                    return Json(GetFailureMessageResponse(result));
                }
            }
            return Json(deleteSampleListViewModel);
        }

        public async Task<IActionResult> Items(int id, CancellationToken cancellationToken)
        {
            var result = await mediator.Send(new GetSampleItemsByListId.Query(id), cancellationToken);

            return PartialView("_ItemList", result.Value.Adapt<List<SampleItemViewModel>>());
        }

        [HttpPost]
        public async Task<IActionResult> AddItem(SampleItemViewModel sampleItemViewModel, CancellationToken cancellationToken)
        {
            Result addItemResult = null;
            if (ModelState.IsValid)
            {
                addItemResult = await mediator.Send(
                    new AddSampleItemToList.Command(
                        sampleItemViewModel.ListId,
                        sampleItemViewModel.Adapt<SampleItemDto>()), cancellationToken: cancellationToken);

                if (addItemResult.IsFailure)
                {
                    return Json(GetFailureMessageResponse(addItemResult, "AddItemValidations"));
                }
            }

            var partialViewContent = await razorViewRenderer.RenderPartialViewAsync("_Item", sampleItemViewModel, ControllerContext);

            // Devolver el contenido del partial view como JSON
            return Json(new { success = true, content = partialViewContent });
        }

        [HttpPost]
        public async Task<IActionResult> RemoveItem(SampleItemViewModel sampleItemViewModel, CancellationToken cancellationToken)
        {
            var result = await mediator.Send(
                new RemoveSampleItemFromList.Command(
                    sampleItemViewModel.ListId,
                    sampleItemViewModel.Id), cancellationToken: cancellationToken);


            if (result.IsFailure)
            {
                return Json(GetFailureMessageResponse(result, elementId: "Items"));
            }
            else
            {
                return Json(GetSuccessMessageResponse(localizer.GetString("Sample_SampleList_RemoveItem_Success"), elementId: "Items"));
            }
        }

        private async Task<Result<List<SampleListWithItemsCountDto>>> ListByLoggedUserAsync(CancellationToken cancellationToken)
        {
            var user = await userManager.GetUserAsync(UserPrincipal);

            return await mediator.Send(new ListSampleListByUser.Query(user), cancellationToken);
        }

        private async Task<Result<SampleListWithItemsDto>> GetSampleListByIdAsync(int id, string elementId = null, CancellationToken cancellationToken = default)
        {
            var result = await mediator.Send(new GetSampleListById.Query(id), cancellationToken);

            if (result.IsFailure)
            {
                HandleFailureResult(result, elementId);
            }

            return result;
        }
    }
}

src/Template/Template.WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http.Extensions;
@using Microsoft.Extensions.Localization;
@using Microsoft.Extensions.Options;
@using System.Globalization;
@using Template.Application.Features.IdentityContext;
@using Template.Configuration;
@using Template.Security.Authorization;
@using Template.WebApp.Extensions;
@using Template.Application.Features.IdentityContext.Services;

@inject SignInManager SignInManager
@inject UserManager UserManager
@inject IAuthorizationService AuthService;
@inject IStringLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocalizationOptions
@inject AppSettings Settings


@{
    string returnUrl = ViewContext.HttpContext.Request.GetEncodedPathAndQuery();
    var requestCultureFeature = Context.GetRequestCultureFeature();
    var requestCulture = requestCultureFeature.RequestCulture.UICulture.Name.Length == 2 ? requestCultureFeature.RequestCulture.UICulture.Name : requestCultureFeature.RequestCulture.UICulture.Parent.Name;
    var cultureItems = LocalizationOptions.Value.SupportedUICultures
                        .Where(c => c.ToString().Length == 2)
                        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName.ToUpper() })
                        .ToList();
    var currentLang = cultureItems.Find(x => x.Value == CultureInfo.CurrentUICulture.TwoLetterISOLanguageName);

    var isAdmin = (await AuthService.AuthorizeAsync(User, Policies.AdminUser)).Succeeded;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Template.WebApp</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/Content/theme/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/Content/theme/site.min.css" />
    </environment>
    <link rel="stylesheet" href="~/Content/vendors/bootstrap-icons/font/bootstrap-icons.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-blue-1 border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Template</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">@Localizer["Layout_Navbar_Home"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">@Localizer["Layout_Navbar_Privacy"]</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            @if (Settings.Samples.ShowSampleMVC)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="SampleMvc" asp-controller="SampleList" asp-action="Index">@Localizer["Layout_Navbar_SampleList_MVC"]</a>
                                </li>
                            }
                            @if (Settings.Samples.ShowSampleAjax)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="SampleAjax" asp-controller="SampleList" asp-action="Index">@Localizer["Layout_Navbar_SampleList_Ajax"]</a>
                                </li>
                            }

                            if (isAdmin)
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownManage" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@Localizer["Layout_Navbar_Administration_Manage"]</a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownManage">
                                        <a class="dropdown-item" asp-area="Administration" asp-controller="Users" asp-action="Index">@Localizer["Layout_Navbar_Administration_Users"]</a>
                                        <a class="dropdown-item" asp-area="Administration" asp-controller="Roles" asp-action="Index">@Localizer["Layout_Navbar_Administration_Roles"]</a>
                                    </div>
                                </li>
                            }
                        }
                    </ul>
                    <ul class="navbar-nav d-flex flex-row">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownLanguages" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <span class="c-gray-520 mr-05 font-sm text-white text-uppercase">@currentLang.Value</span>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownLanguages">
                                @foreach (var language in cultureItems.FindAll(x => x != currentLang))
                                {
                                    <li>
                                        <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="@language.Value" asp-route-returnUrl="@returnUrl">
                                            <img width="27" height="19" src="~/Content/images/flags/@(language.Value).svg" alt="@language.Text">
                                            <span class="c-md ms-4 text-capitalize">@language.Text</span>
                                        </a>
                                    </li>
                                }
                            </ul>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <section class="section-bar mb-4">
        @await RenderSectionAsync("SectionBar", required: false)
    </section>
    <div class="container" style="position: relative;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer bg-blue-3 border-top text-white text-center">
        <div class="container">
            &copy; 2024 - Template.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-white">@Localizer["Layout_Footer_Privacy"]</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/Content/vendors/jquery.bundle.js"></script>
        <script src="~/Content/vendors/bootstrap.bundle.js"></script>
        <script src="~/Content/js/ui-components/message-taghelper/message-taghelper.bundle.js"></script>
        <script src="~/Content/vendors/references.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/Content/vendors/jquery.bundle.min.js"></script>
        <script src="~/Content/vendors/bootstrap.bundle.min.js"></script>
        <script src="~/Content/js/ui-components/message-taghelper/message-taghelper.bundle.min.js"></script>
    </environment>

    @await RenderSectionAsync("scripts", required: false)
</body>
</html>

src/Template/Template.WebApp/Views/Shared/_LayoutError.cshtml
@using Microsoft.AspNetCore.Http.Extensions;
@using Microsoft.Extensions.Localization;
@using Microsoft.Extensions.Options;
@using System.Globalization;
@using Template.Application.Features.IdentityContext;
@using Template.Security.Authorization;
@using Template.WebApp.Extensions;
@using Template.Application.Features.IdentityContext.Services;

@inject SignInManager SignInManager
@inject UserManager UserManager
@inject IAuthorizationService AuthService;
@inject IOptions<RequestLocalizationOptions> LocalizationOptions
@inject IStringLocalizer Localizer


@{
    string returnUrl = ViewContext.HttpContext.Request.GetEncodedPathAndQuery();
    var requestCultureFeature = Context.GetRequestCultureFeature();
    var requestCulture = requestCultureFeature.RequestCulture.UICulture.Name.Length == 2 ? requestCultureFeature.RequestCulture.UICulture.Name : requestCultureFeature.RequestCulture.UICulture.Parent.Name;
    var cultureItems = LocalizationOptions.Value.SupportedUICultures
                        .Where(c => c.ToString().Length == 2)
                        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName.ToUpper() })
                        .ToList();
    var currentLang = cultureItems.Find(x => x.Value == CultureInfo.CurrentUICulture.TwoLetterISOLanguageName);

    var isAdmin = (await AuthService.AuthorizeAsync(User, Policies.AdminUser)).Succeeded;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Template.WebApp</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/Content/theme/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/Content/theme/site.min.css" />
    </environment>
    <link rel="stylesheet" href="~/Content/vendors/bootstrap-icons/font/bootstrap-icons.min.css" />
</head>
<body class="body-error">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-blue-1 border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Template</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer bg-blue-3 border-top text-white text-center">
        <div class="container">
            &copy; 2024 - Template.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-white">@Localizer["Layout_Footer_Privacy"]</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/Content/vendors/jquery.slim.js"></script>
        <script src="~/Content/vendors/bootstrap.bundle.js"></script>
        <script src="~/Content/vendors/references.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/Content/vendors/jquery.slim.min.js"></script>
        <script src="~/Content/vendors/bootstrap.bundle.min.js"></script>
    </environment>
</body>
</html>

src/Template/Template.WebApp/Views/Shared/_ResponseMessage.cshtml
@using Microsoft.AspNetCore.Mvc.ModelBinding;
@using Template.Common;
@using Template.Configuration;
@model (ModelStateDictionary ModelState, ErrorType ErrorType);

@if (Model.ModelState != null && !Model.ModelState.IsValid)
{
    <div class="validation-summary-errors">
        @if (Model.ErrorType == ErrorType.All | Model.ErrorType == ErrorType.Generics)
        {
            @foreach (var modelError in Model.ModelState.Where(kv => kv.Key == Constants.KeyErrors.GenericError.Value).SelectMany(keyValuePair => keyValuePair.Value.Errors))
            {
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    @*<h4 class="alert-heading">ERROR</h4>*@
                    <span>@modelError.ErrorMessage</span>
                </div>
            }
        }
        @if ((Model.ErrorType == ErrorType.All | Model.ErrorType == ErrorType.Validations) && Model.ModelState.Any(kv => kv.Key == Constants.KeyErrors.ValidationError.Value))
        {
            <ul>
                @foreach (var modelError in Model.ModelState.Where(kv => kv.Key == Constants.KeyErrors.ValidationError.Value).SelectMany(keyValuePair => keyValuePair.Value.Errors))
                {
                    <li>@modelError.ErrorMessage</li>
                }
            </ul>
        }
    </div>

}

src/Template/Template.WebApp/Views/Shared/_SectionBar.cshtml
@model string
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container-fluid section-bar-content pt-2 pb-2">
    <h3>@Model</h3>
</div>